config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup",  to: "members#new"
  get  "/login",   to: "sessions#new"
  post "/login",   to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :members do
    member do
      get :following
      get :followers
    end
  end
  resources :account_activations, only: [ :edit ]
  resources :password_resets,     only: [ :new, :create, :edit, :update ]
  resources :microposts,          only: [ :create, :destroy ]
  resources :relationships,       only: [ :create, :destroy ]
  get "/microposts", to: "static_pages#home"
end

app/views/shared/_error_messages.html.erb
<% object = local_assigns[:object] || @member %>
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items %>
<% end %>

app/views/shared/_member_info.html.erb
<div class="text-center">
  <%= link_to gravatar_for(current_member, size: 80), current_member %>
  <h1><%= current_member.name %></h1>
  <span><%= link_to "view my profile", current_member, class: "btn btn-outline-secondary btn-sm" %></span>
  <span class="d-block mt-2"><%= pluralize(current_member.microposts.count, "micropost") %></span>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="mb-3">
    <%= f.text_area :content, placeholder: "Compose new micropost...", class: "form-control", rows: 3 %>
  </div>
  <div class="mb-3">
    <span class="image">
      <%= f.file_field :image, class: "form-control" %>
    </span>
  </div>
  <div class="d-grid">
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @member ||= current_member %>
<div class="stats">
  <a href="<%= following_member_path(@member) %>">
    <strong id="following" class="stat">
      <%= @member.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_member_path(@member) %>">
    <strong id="followers" class="stat">
      <%= @member.followers.count %>
    </strong>
    followers
  </a>
</div>